[data]
x = "x_location"
y = "y_location"
z = "z_location"
gene = "feature_name"
min_molecules_per_cell = 150

[segmentation]
prior_segmentation_confidence = 0.8
scale = 15
scale_std = "85%"
n_cells_init = 17002


[plotting]

