[data]
x = "x_location"
y = "y_location"
z = "z_location"
gene = "feature_name"
min_molecules_per_cell = 150

[segmentation]
prior_segmentation_confidence = 0.5
scale = 12
scale_std = "25%"
n_cells_init = 39000


[plotting]

