FROM quay.io/rgrindle/rename_transcripts_xenium:v1.1.1

RUN apt-get install gzip -y

RUN wget -O xeniumranger-3.1.1.tar.gz "https://cf.10xgenomics.com/releases/xeniumranger/xeniumranger-3.1.1.tar.gz?Expires=1756876021&Key-Pair-Id=APKAI7S6A5RYOXBWRPDA&Signature=atAZ3i4c3teaR3DtVIzPM8PN6xOM2~CMXkhvIMldBJW-DqCgBrkWBcZJZ0yak3mOJA7Rzr~hsB-k7tc7d-4l9jfPILWzNyUZZhUcbOX8rCNPyWjvHH~CqktpBWcEIq5NcmNspLN0feHIG5Bpd~Fwzkk1IsJdx2Y8looX7fUcZGXdw-~C5WbfomP8lBMfmCoce9MRabFwHllb6KoEnJ3Tn4uLQa1kyayeGbRGejFAKrh8uvSFNcuYbplRULVVV9ssa7rz83k7T2DwSpmuEU4EtA3Ox7BXERFQ5GOzupOs7e0v38vY0kwiMj8AQTSRr7poT7HsuUXMKhi975jUMuX1ag__"

RUN tar -xzvf xeniumranger-3.1.1.tar.gz

RUN mv xeniumranger-xenium3.1  /usr/local/bin/

WORKDIR /mnt

ENV gene_panel /mnt/gene_panel.json
ENV features /mnt/custom_features.tsv
ENV xenium /mnt/

RUN sed -i.bak 's|modified-panel.json|/mnt/modified-panel.json|' /usr/local/bin/rename_gene_panel.py

ENTRYPOINT rename_gene_panel.py --gene_panel $gene_panel --map $features; modified=/mnt/modified-panel.json; /usr/local/bin/xeniumranger-xenium3.1/bin/xeniumranger relabel --id=relabled --xenium-bundle=$xenium --panel=$modified --localcores=32 --localmem=128
